export const jobs = [
  {
    id: 1,
    title: 'Jobs Company',
    location: 'Ukraine, Vinnitsia',
    address: 'Saint Laurent Boulevard between Rue Sherbrooke and Rue Saint Viateur, Montreal, Quebec',
    salary: '300$',
    jobName: 'Front-end Developer',
    jobType: 'IT Technology',
    employment: 'Full-time',
    contacts: 'Full Name, +104345234',
    education: 'education',
    required: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in. Maecenas sed hendrerit arcu. Vivamus euismod libero a placerat venenatis. Donec mattis, risus nec vestibulum dictum, lacus justo semper est, eget dictum mi ligula sed ex. Sed imperdiet velit lacus. Quisque in nibh ac ligula dictum molestie. Quisque scelerisque facilisis purus, ut dignissim arcu vestibulum vitae.',
  },
  {
    id: 2,
    title: 'Netflix',
    location: 'USA, California',
    address: 'Rue du Petit Champlain, Quebec City, Quebec',
    salary: '500$ - 1000$',
    jobName: 'Back-end Developer',
    jobType: 'IT Technology',
    employment: 'Full-time',
    contacts: 'Full Name, +767545345',
    education: 'education',
    required: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in. Maecenas sed hendrerit arcu. Vivamus euismod libero a placerat venenatis. Donec mattis, risus nec vestibulum dictum, lacus justo semper est, eget dictum mi ligula sed ex. Sed imperdiet velit lacus. Quisque in nibh ac ligula dictum molestie. Quisque scelerisque facilisis purus, ut dignissim arcu vestibulum vitae.',
  },
  {
    id: 3,
    title: 'EPAM',
    location: 'Ukraine, Kiev',
    address: 'Argyle Street, Halifax, Nova Scotia',
    salary: '100$',
    jobName: 'Cleaner',
    jobType: 'Support',
    employment: 'Full-time',
    contacts: 'John Dou, +762412303',
    education: 'Education',
    required: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in. Maecenas sed hendrerit arcu. Vivamus euismod libero a placerat venenatis. Donec mattis, risus nec vestibulum dictum, lacus justo semper est, eget dictum mi ligula sed ex. Sed imperdiet velit lacus. Quisque in nibh ac ligula dictum molestie. Quisque scelerisque facilisis purus, ut dignissim arcu vestibulum vitae.',
  },
  {
    id: 4,
    title: 'Google',
    location: 'China, Shanghai',
    address: 'George Street, St. John’s, Newfoundland & Labrador',
    salary: '3000$',
    jobName: 'Full-stack developer',
    jobType: 'IT Technology, web solutions',
    employment: 'Full-time',
    contacts: 'John Dou, +762412303',
    education: 'Education',
    required: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat mollis enim, id placerat nisl faucibus in. Maecenas sed hendrerit arcu. Vivamus euismod libero a placerat venenatis. Donec mattis, risus nec vestibulum dictum, lacus justo semper est, eget dictum mi ligula sed ex. Sed imperdiet velit lacus. Quisque in nibh ac ligula dictum molestie. Quisque scelerisque facilisis purus, ut dignissim arcu vestibulum vitae.',
  }
];